import type { ConsoleStatus } from "./castercloud-console-data";

export type AppDeploymentStatus = ConsoleStatus | "prepared";

export type AppDeploymentItem = {
  id: string;
  name: string;
  kind: "site" | "miniapp" | "agent" | "service" | "channel" | "docs";
  route: string;
  target: string;
  status: AppDeploymentStatus;
  deployEndpoint: string;
  evidence: string[];
  blockers: string[];
  retirementImpact: string;
};

export type DocsSection = {
  id: string;
  title: string;
  body: string;
  bullets: string[];
};

export const appDeploymentCatalog: AppDeploymentItem[] = [
  {
    id: "casterchain-online",
    name: "casterchain.online",
    kind: "site",
    route: "https://casterchain.online",
    target: "CStorage shell, CasterRPC gateway, Caster event log, Caster snapshots",
    status: "gated",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["acceptance matrix", "burn-in report", "rollback drill", "production smoke"],
    blockers: ["final retirement denies Vercel/Postgres/Redis/R2", "burn-in window incomplete"],
    retirementImpact: "Unlocks frontend and API cutover only after strict acceptance.",
  },
  {
    id: "gitcaster",
    name: "GitCaster",
    kind: "site",
    route: "/",
    target: "CStorage static export plus CasterCloud Console",
    status: "ready",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["static export", "console API smoke", "proof envelope"],
    blockers: ["public console/API deploy target evidence still needed"],
    retirementImpact: "Becomes the operator and builder front door for the CasterCloud stack.",
  },
  {
    id: "castercloud-console",
    name: "CasterCloud Console",
    kind: "service",
    route: "/console",
    target: "self-owned console UI and wallet-gated API facade",
    status: "prepared",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["service catalog", "OpenAPI docs", "wallet smoke", "dry-run request journal"],
    blockers: ["CASTERCLOUD_CONSOLE_PUBLIC_BASE_URL", "CASTERCLOUD_CONSOLE_API_BASE_URL"],
    retirementImpact: "Reduces QConsole reliance by moving operator workflows to Caster-owned endpoints.",
  },
  {
    id: "casteragents",
    name: "CasterAgents",
    kind: "agent",
    route: "/miniapps/casteragents",
    target: "CasterCloud worker facade and notification proof lane",
    status: "blocked",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["admin kill switch", "signer lifecycle", "production route smoke"],
    blockers: ["Farcaster mobile screenshots", "notification delivery proof", "external-proof.input.json"],
    retirementImpact: "Keeps social automation disabled from final completion until real user proof exists.",
  },
  {
    id: "caster-studio",
    name: "Caster Studio",
    kind: "miniapp",
    route: "/miniapps/creator",
    target: "wallet-gated miniapp builder, preview, and launch packet service",
    status: "blocked",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["PR1 launch packet", "PR2 routes", "PR3 DB store", "PR7 Farcaster metadata"],
    blockers: ["live route proof", "Farcaster manifest/card live evidence"],
    retirementImpact: "Unlocks app-builder launch only after live Farcaster rendering proof.",
  },
  {
    id: "hypersnap-channels",
    name: "HyperSnap Channels",
    kind: "channel",
    route: "/hypersnap",
    target: "invite queue, reply-cast proof, and membership reconciliation",
    status: "blocked",
    deployEndpoint: "POST /v1/hypersnap/invites",
    evidence: ["invite queue plan", "candidate FIDs", "reply evidence schema"],
    blockers: ["live reply-cast.json", "membership-reconciliation.json"],
    retirementImpact: "Blocks social channel completion until external channel evidence is real.",
  },
  {
    id: "casterexchange",
    name: "CasterExchange",
    kind: "site",
    route: "https://www.casterexchange.online",
    target: "existing CStorage static mirror",
    status: "ready",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["custom domain", "static bucket", "published shell"],
    blockers: ["none for current static mirror"],
    retirementImpact: "Reference implementation for static CStorage app hosting.",
  },
  {
    id: "casterpad",
    name: "CasterPad",
    kind: "miniapp",
    route: "/casterpad",
    target: "CStorage shell plus CQueue publish queue",
    status: "planned",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["fee-vault deploy plan", "app manifest"],
    blockers: ["deployment manifest", "queue evidence"],
    retirementImpact: "Adds a wallet-published miniapp lane after the base console is public.",
  },
  {
    id: "casterpunks",
    name: "CasterPunks",
    kind: "miniapp",
    route: "/casterpunks",
    target: "CStorage shell plus CQuark asset registry",
    status: "planned",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["asset registry", "ownership receipt"],
    blockers: ["asset ownership policy", "CQuark registry evidence"],
    retirementImpact: "Depends on CQuark-style asset registry before public claims.",
  },
  {
    id: "casterclaim",
    name: "CasterClaim",
    kind: "miniapp",
    route: "/claim",
    target: "wallet claim miniapp, proof receipt, and rate-limit policy",
    status: "planned",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["claim proof envelope", "rate-limit receipt"],
    blockers: ["claim policy", "abuse/rate evidence"],
    retirementImpact: "Moves claims behind wallet receipts instead of hosted console keys.",
  },
  {
    id: "casterschool",
    name: "CasterSchool",
    kind: "miniapp",
    route: "/school",
    target: "CStorage content app and learner progress event log",
    status: "planned",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["content manifest", "progress schema"],
    blockers: ["curriculum manifest", "privacy allowlist"],
    retirementImpact: "Uses snapshots for public content and private receipts for progress.",
  },
  {
    id: "castera1",
    name: "CasterA1",
    kind: "agent",
    route: "/a1",
    target: "agent route, usage ledger, and CQueue worker pipeline",
    status: "planned",
    deployEndpoint: "POST /v1/deployments",
    evidence: ["usage ledger", "worker queue receipt"],
    blockers: ["AI usage custody", "queue proof"],
    retirementImpact: "Requires usage metering before replacing hosted billing style controls.",
  },
];

export const castercloudDocsSections: DocsSection[] = [
  {
    id: "overview",
    title: "Overview",
    body: "CasterCloud is the Caster-owned console, API facade, and deployment registry for GitCaster, casterchain.online, and the miniapp stack.",
    bullets: [
      "It mirrors the useful QConsole service surfaces without claiming to be the official hosted Quilibrium provider.",
      "It points to our AWS node, local laptop node, CasterRPC gateway, event logs, snapshots, and proof envelopes.",
      "It keeps production cutover gated by the same truth table: passed, blocked_external, fixture_only, failed.",
      "GET /v1/service-actions exposes wallet-gated dry-run templates for every owned service surface.",
    ],
  },
  {
    id: "service-api-reference",
    title: "Service API Reference",
    body: "CasterCloud now serves a first-party service API reference so operators can stop guessing from hosted QConsole screens and route Caster apps through owned endpoints.",
    bullets: [
      "GET /v1/docs/castercloud/services returns the full owned service reference for CStorage, CKeys, CIdentity, CCredentials, CQueue, CPing, HyperSnap, CQuark, deployments, public endpoints, usage ledger, and docs.",
      "GET /v1/docs/castercloud/services/{id} returns one service entry with canonical routes, QConsole-style aliases, auth model, dry-run behavior, evidence paths, and strict blockers.",
      "GET /v1/qconsole/docs/services exposes the same reference through a QConsole-compatible alias.",
      "CStorage keeps the QStorage mental model, including S3-compatible object storage behavior through owned endpoints.",
      "CKeys keeps the QKMS mental model, including KMS-compatible key-management behavior through owned endpoints.",
      "The reference records that official Quilibrium API docs still use QConsole Credentials for hosted services, while CasterCloud serves the Caster-owned facade and does not claim to be the official hosted QConsole provider.",
    ],
  },
  {
    id: "wallets",
    title: "Wallet Sessions",
    body: "Console users deploy with wallet signatures. The API issues a session only after signature verification succeeds.",
    bullets: [
      "User wallet keys stay in the browser.",
      "Admin, treasury, service, and operator keys never enter NEXT_PUBLIC env.",
      "Live mutation requires both a wallet policy receipt and explicit operator live flags.",
      "Service actions use POST /v1/wallet/session first, then write local dry-run receipts until live gates pass.",
    ],
  },
  {
    id: "public-endpoints",
    title: "Public Endpoints",
    body: "CasterCloud binds the owned console, docs, and API facade to Caster-controlled public endpoints instead of requiring hosted QConsole for day-to-day app operations.",
    bullets: [
      "GET /v1/public-endpoints/binder returns the endpoint contract, DNS safety template, and strict readiness blockers.",
      "GET /v1/qconsole/public-endpoints exposes the same binder through a QConsole-style alias.",
      "GET /v1/public-endpoints/env-intake loads ignored operator env files without printing values and reruns the binder in the safe order.",
      "GET /v1/public-endpoints/target-candidates derives redacted DNS target candidates from node/deploy evidence and refuses URLs or path values.",
      "GET /v1/public-endpoints/target-confirmation records operator confirmation of target hashes without exposing raw target values.",
      "GET /v1/public-endpoints/target-signing-handoff returns the redacted wallet handoff packet and current blocker before any signature is imported.",
      "GET /v1/public-endpoints/target-confirmation/message returns the exact wallet-signable target hash confirmation.",
      "POST /v1/public-endpoints/target-confirmation/import verifies the wallet signature and only writes ignored local evidence when allowLocalImport=true.",
      "GET /v1/public-target-wallet-readiness chains public URL, target hash, wallet allowlist, workbench, migration status, and completion checks without printing secrets.",
      "GET /v1/qconsole/public-target-wallet-readiness exposes the same chain through a QConsole-compatible alias.",
      "GET /v1/public-endpoints/publish-readiness returns the final public endpoint publish-readiness chain, current blocker, and next exact prompt.",
      "GET /v1/qconsole/public-endpoint-publish-readiness exposes publish readiness through a QConsole-compatible alias.",
      "GET /v1/console/public-console-env returns the public console/API endpoint env workbench with redacted URL status.",
      "POST /v1/console/public-console-env/import validates and optionally stages the ignored local public console/API endpoint env.",
      "GET /v1/qconsole/public-console-env and POST /v1/qconsole/public-console-env/import expose the same env workbench through QConsole-compatible aliases.",
      "GET /v1/console/operator-evidence-workbench returns the two wallet signing jobs needed for target confirmation and operator allowlist evidence.",
      "GET /v1/qconsole/operator-evidence-workbench exposes the operator evidence workbench through a QConsole-compatible alias.",
      "GET /v1/console/operator-evidence-bundle returns the combined target-confirmation and allowlist importer status.",
      "POST /v1/console/operator-evidence-bundle/import verifies both wallet signatures and only writes ignored local evidence when allowLocalImport=true.",
      "GET /v1/qconsole/operator-evidence-bundle and POST /v1/qconsole/operator-evidence-bundle/import expose the same bundle flow through QConsole-compatible aliases.",
      "GET /v1/console/owned-readiness aggregates the owned console replacement chain before any hosted QConsole retirement claim.",
      "GET /v1/qconsole/owned-console-readiness exposes that owned readiness chain through a QConsole-compatible alias.",
      "GET /v1/console/current-blocker returns the current blocker, external evidence list, and redacted local artifact summary.",
      "GET /v1/qconsole/current-blocker exposes the current blocker through a QConsole-compatible alias.",
      "GET /v1/console/next-exact-prompt returns the exact next local/operator action prompt without printing secrets.",
      "GET /v1/qconsole/next-exact-prompt exposes the next exact prompt through a QConsole-compatible alias.",
      "GET /v1/console/final-evidence/requirements returns final external evidence requirements, missing files, and schema-blocked proof status without printing file contents.",
      "GET /v1/qconsole/final-evidence/requirements exposes the same requirements through a QConsole-compatible alias.",
      "GET /v1/console/service-creation-matrix lists every owned service creation flow and the bulk dry-run provisioning request.",
      "GET /v1/qconsole/service-creation-matrix exposes the service creation matrix through a QConsole-compatible alias.",
      "GET /v1/console/node-bindings maps every owned service to AWS primary node, laptop backup node, and local proof evidence.",
      "GET /v1/qconsole/node-bindings exposes the same node binding matrix through a QConsole-compatible alias.",
      "cloud.casterchain.online is reserved for the console, docs, and owned API facade; api.casterchain.online is reserved for the CasterRPC runtime gateway.",
      "DNS mutation remains outside the binder and requires explicit live flags, rollback evidence, and final cutover gates.",
    ],
  },
  {
    id: "credentials",
    title: "Self-Owned Credentials",
    body: "CasterCloud serves its own credential issuer contract for CasterCloud endpoints so operators and users do not need hosted QConsole keys for our app stack.",
    bullets: [
      "GET /v1/credentials/issuer returns the issuer contract, credential kinds, and safety policy.",
      "GET /v1/qconsole/credentials exposes the same issuer through a QConsole-style alias.",
      "POST /v1/iam/access-keys and POST /v1/qconsole/credentials require a wallet session and default to dry-run receipts.",
      "Reports only contain public ids, request hashes, scope hashes, and redacted receipt metadata; secrets are generated outside public artifacts.",
    ],
  },
  {
    id: "services",
    title: "Services",
    body: "The console exposes CStorage, CKeys, CIdentity, CQueue, CPing, HyperSnap, CQuark, Deployments, and Usage Ledger surfaces.",
    bullets: [
      "CStorage owns objects, static exports, snapshots, and proof artifacts.",
      "CQueue and CPing replace hosted queue and notification workflows only after live evidence exists.",
      "CKeys can use QKMS-compatible receipts or a Caster-owned custody policy, but private key material is never printed.",
    ],
  },
  {
    id: "deployments",
    title: "App Deployment",
    body: "Every app and miniapp is registered before public deployment so blockers stay visible.",
    bullets: [
      "GitCaster and casterchain.online are treated as first-class deployment targets.",
      "CasterAgents, Caster Studio, and HyperSnap stay blocked until external Farcaster and channel proof exists.",
      "Deployment requests are journaled dry-run locally unless live deploy flags are explicitly present.",
      "GET /v1/deployments/workbench and GET /v1/qconsole/deployments/workbench expose the single owned app and miniapp deploy workbench.",
      "GET /v1/public-target-wallet-readiness shows the current blocker before any app or miniapp can be promoted to a live public target.",
      "GET /v1/deployments/manifests exposes wallet-signable request hashes for each app and miniapp.",
      "GET /v1/deployments/queue exposes the guarded public deploy queue used by cloud.casterchain.online.",
      "GET /v1/deployments/journal exposes wallet-shaped dry-run deployment receipts, including GitCaster.",
      "GET /v1/deployments/approvals exposes operator wallet approval receipts without exposing private keys.",
      "GET /v1/console/public-console-env and POST /v1/console/public-console-env/import stage the console/API base URLs before live public publish.",
      "GET /v1/console/current-blocker and GET /v1/console/next-exact-prompt keep the next required operator action visible inside the owned console.",
      "GET /v1/console/final-evidence/requirements keeps the evidence dropzone checklist visible before final retirement gates.",
      "GET /v1/console/operator-evidence-workbench exposes the target-confirmation and allowlist signing jobs needed before live public publish.",
      "GET /v1/console/operator-evidence-bundle and POST /v1/console/operator-evidence-bundle/import combine target-confirmation plus allowlist wallet proofs for the final public publish chain.",
      "GET /v1/iam/operators/allowlist exposes signed operator allowlist evidence for self-owned approvals.",
      "GET /v1/iam/operators/allowlist/message and POST /v1/iam/operators/allowlist/import support browser-wallet allowlist bootstrap.",
      "GET /v1/deployments/approvals/:id/message and POST /v1/deployments/approvals/:id/import support browser-wallet approval evidence.",
    ],
  },
  {
    id: "provisioning",
    title: "Provisioning",
    body: "CasterCloud exposes a wallet-gated provisioning layer for owned buckets, keys, credentials, queues, topics, assets, and app redeployments.",
    bullets: [
      "GET /v1/provisioning/actions returns the CasterCloud service provisioning catalog.",
      "GET /v1/qconsole/provisioning exposes the same catalog through a QConsole-style alias.",
      "GET /v1/console/service-creation-matrix returns the create-all service request and per-service request hashes.",
      "GET /v1/console/node-bindings proves the creation matrix is backed by node evidence before strict live promotion.",
      "POST /v1/provisioning/requests requires a wallet session and writes dry-run receipts by default.",
      "Live provisioning requires completion, rollback evidence, operator allowlist evidence, and explicit allow flags.",
    ],
  },
  {
    id: "docs",
    title: "API Docs",
    body: "CasterCloud publishes its own API overview and OpenAPI document for local and node-hosted operators.",
    bullets: [
      "GET /v1/docs/openapi.json returns machine-readable API routes.",
      "GET /v1/docs/castercloud returns the CasterCloud service contract and safety policy.",
      "GET /v1/apps and GET /v1/deployments/catalog expose the deployable app catalog.",
    ],
  },
  {
    id: "provider",
    title: "Self-Owned Provider",
    body: "The provider contract defines which CasterCloud endpoints replace hosted QConsole operator dependency and which items remain evidence-gated.",
    bullets: [
      "GET /v1/provider/castercloud returns the CasterCloud service authority map.",
      "GET /v1/qconsole/provider returns the same contract through a QConsole-compatible alias.",
      "GET /v1/console/node-bindings returns the AWS and laptop-node binding matrix used by the owned console.",
      "The contract marks CStorage, CKeys, CIdentity, CQueue, CPing, HyperSnap, CQuark, Deployments, Usage Ledger, and Docs surfaces.",
      "The contract explicitly avoids claiming to be the official hosted QConsole provider or replacing the Quilibrium network.",
    ],
  },
  {
    id: "self-owned-stack",
    title: "Self-Owned Stack Status",
    body: "The stack status endpoint aggregates every owned CasterCloud replacement surface so operators can see what is local, what is wallet-gated, and what remains externally blocked.",
    bullets: [
      "GET /v1/castercloud/self-owned-stack returns the aggregate service ownership matrix, QConsole replacement status, source report statuses, and strict blockers.",
      "GET /v1/qconsole/self-owned-stack exposes the same status through a QConsole-compatible alias.",
      "The report can pass local wiring while keeping strict readiness blocked until real public endpoint, wallet signature, completion, burn-in, and retirement evidence exists.",
    ],
  },
];
