export const GITCASTER_ERROR_CODES = [
  "gitcaster.error.invalid_did",
  "gitcaster.error.invalid_signature",
  "gitcaster.error.invalid_capability",
  "gitcaster.error.capability_expired",
  "gitcaster.error.capability_scope_denied",
  "gitcaster.error.capability_resource_mismatch",
  "gitcaster.error.nonce_replay",
  "gitcaster.error.timestamp_skew",
  "gitcaster.error.payload_hash_mismatch",
  "gitcaster.error.ref_from_mismatch",
  "gitcaster.error.ref_force_push_disabled",
  "gitcaster.error.ref_delete_disabled",
  "gitcaster.error.object_missing",
  "gitcaster.error.object_hash_mismatch",
  "gitcaster.error.qstorage_endpoint_missing",
  "gitcaster.error.qstorage_verify_failed",
  "gitcaster.error.castercloud_endpoint_missing",
  "gitcaster.error.castercloud_verify_failed",
  "gitcaster.error.domain_registry_missing",
  "gitcaster.error.token_contract_required",
  "gitcaster.error.audit_required",
  "gitcaster.error.secret_risk",
  "gitcaster.error.sensitive_state_redacted",
  "gitcaster.error.preview_data_only",
  "gitcaster.error.external_blocker",
] as const;

export type GitCasterErrorCode = (typeof GITCASTER_ERROR_CODES)[number];
