import { sitePath } from "../../../lib/site-url";

const publicArtifacts = [
  ["Catalog module", "packages/ecosystem/src/app-shell-catalog.ts", "Typed shell catalog entries derived from the proof-aware ecosystem RC directory."],
  ["Local fixture", "examples/app-shells/gitcaster-app-shell-catalog.local.json", "Local preview routes, dependency-risk labels, and blocked native deployment claims."],
  ["Caster Intelligence fixture", "examples/app-shells/caster-intelligence.local-shell.json", "Redacted builder-tool shell metadata and data-rights blockers."],
  ["Generated catalog", "apps/web/public/gitcaster-app-shell-catalog.json", "Public JSON catalog for app and miniapp shell review."],
  ["Preview smoke", "apps/web/public/gitcaster-app-shell-local-preview-smoke.json", "Static route smoke status for local app and miniapp previews."],
  ["Strict checker", "scripts/ecosystem/check-app-shell-catalog-public-alpha.cjs", "Deterministic gate that rejects live runtime, native deploy, QStorage, domain, and production claims."],
  ["Evidence", "launch/evidence/app-shell-catalog-public-hardening-source.json", "Proof file generated by the public-alpha checker."]
];

const dependencyRiskLabels = [
  ["Runtime API", "local-fixture-only", "Local fixture shape only. No live runtime endpoint is claimed."],
  ["Native storage", "blocked_external", "QStorage publication proof is required before stronger labels."],
  ["Native domain", "blocked_external", ".caster registry and route proof are required before stronger labels."],
  ["Managed runtime", "blocked_external", "Managed CasterCloud orchestration stays closed and proof-gated."],
  ["Legacy hosted platform", "legacy-reference", "Legacy hosted files can be referenced only as migration context."]
];

const blockedClaims = [
  "native .caster deployment",
  "QStorage publication",
  "managed runtime endpoint",
  "production readiness",
  "external audit completion",
  "custody, billing, rollback, or managed operation readiness"
];

export default function AppShellCatalogOpenSourcePage() {
  return (
    <div className="stack">
      <section className="section">
        <div className="eyebrow">Open-core layer</div>
        <h1>App shell catalog hardening</h1>
        <p className="lede">
          GitCaster now publishes a proof-aware app and miniapp shell catalog for
          local preview routing, manifest review, dependency-risk labels, and
          blocked native deployment claims. This is a public-alpha developer
          layer, not a managed runtime or production deployment.
        </p>
        <div className="actions">
          <a className="button primary" href="https://github.com/casteragents/gitcaster/tree/main/packages/ecosystem">Catalog source</a>
          <a className="button" href="https://github.com/casteragents/gitcaster/tree/main/examples/app-shells">Fixture</a>
          <a className="button" href={sitePath("/gitcaster-app-shell-catalog.json")}>Catalog JSON</a>
          <a className="button" href={sitePath("/open-source/app-shell-local-preview-smoke")}>Preview smoke</a>
          <a className="button" href={sitePath("/ecosystem")}>Preview directory</a>
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Public artifacts</h2>
            <p>These files are safe contribution surfaces for app and miniapp shell review.</p>
          </div>
          <span className="pill good">public-alpha</span>
        </div>
        <div className="grid">
          {publicArtifacts.map(([name, path, description]) => (
            <div className="card" key={name}>
              <h3>{name}</h3>
              <p>{description}</p>
              <span className="pill info">{path}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Dependency-risk labels</h2>
            <p>Runtime and deployment dependencies stay explicit instead of becoming hidden claims.</p>
          </div>
          <span className="pill info">local preview</span>
        </div>
        <div className="grid">
          {dependencyRiskLabels.map(([name, status, description]) => (
            <div className="card" key={name}>
              <div className="row-between">
                <h3>{name}</h3>
                <span className={status === "blocked_external" ? "pill danger" : "pill warn"}>{status}</span>
              </div>
              <p>{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Blocked native claims</h2>
            <p>The catalog deliberately refuses stronger runtime and production labels without proof.</p>
          </div>
          <span className="pill danger">blocked_external</span>
        </div>
        <div className="grid">
          {blockedClaims.map((claim) => (
            <div className="card" key={claim}>
              <p>{claim}</p>
              <span className="pill danger">blocked_external</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Verification command</h2>
            <p>The checker regenerates catalog evidence and rejects unsupported live, deployed, or production claims.</p>
          </div>
          <span className="pill info">deterministic</span>
        </div>
        <pre className="terminal">pnpm run app-shell-preview-smoke:check</pre>
      </section>
    </div>
  );
}
