import { sitePath } from "../../../lib/site-url";

const publicArtifacts = [
  ["CLI deploy command", "apps/cli/src/commands/deploy.ts", "Reads a local GitCaster deploy manifest and writes redacted plan evidence."],
  ["Manifest fixture", "examples/deploy/local-deploy-manifest.example.json", "A local-only app release plan with stronger promotion gates blocked."],
  ["Local evidence", "launch/evidence/cli-deploy-plan-local-dry-run.json", "Generated by the CLI command after manifest validation passes."],
  ["Strict checker", "scripts/cli/check-cli-deploy-plan-public-alpha.cjs", "Verifies redaction, false production claims, blockers, and retired dependency markers."],
  ["Public JSON", "apps/web/public/gitcaster-cli-deploy-plan.json", "Website-readable summary for this public-alpha layer."]
];

const commandFlow = [
  ["Read manifest", "The CLI accepts a gitcaster.deploy-manifest.v1 file from the local workspace."],
  ["Validate safety", "The deploy-manifest package rejects secret-like fields, non-local targets, and unsupported claims."],
  ["Write evidence", "The CLI writes a redacted dry-run evidence file with explicit blockers for promotion."],
  ["Stop before runtime", "No external infrastructure is touched by this public-alpha command."]
];

const blockedGates = [
  ["Managed runtime", "Needs deploy receipt, smoke proof, and rollback proof before any stronger label."],
  ["Native storage", "Needs publish receipt, public read proof, and rollback proof."],
  ["Native domain", "Needs registry receipt and browser smoke proof."],
  ["Custody", "Needs signer reference and redacted custody receipt."],
  ["Billing", "Needs subscription policy and abuse-control proof."],
  ["Release candidate", "Needs audit, node health, runtime, storage, domain, and rollback evidence."]
];

export default function CliDeployPlanOpenSourcePage() {
  return (
    <div className="stack">
      <section className="section">
        <div className="eyebrow">Open-core layer</div>
        <h1>CLI deploy plan dry-run</h1>
        <p className="lede">
          GitCaster now exposes <code>gc deploy plan</code> as a public-alpha
          local planning command. Builders can validate a local manifest and
          produce redacted evidence for review while runtime, custody, billing,
          native storage, native domain, rollback, and release claims stay
          blocked until proof exists.
        </p>
        <div className="actions">
          <a className="button primary" href="https://github.com/casteragents/gitcaster/tree/main/apps/cli">CLI source</a>
          <a className="button" href="https://github.com/casteragents/gitcaster/tree/main/examples/deploy">Manifest fixture</a>
          <a className="button" href={sitePath("/gitcaster-cli-deploy-plan.json")}>Evidence JSON</a>
          <a className="button" href={sitePath("/status")}>Status table</a>
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Public artifacts</h2>
            <p>These files let contributors inspect the command path without gaining managed runtime access.</p>
          </div>
          <span className="pill good">public-alpha</span>
        </div>
        <div className="grid">
          {publicArtifacts.map(([name, path, description]) => (
            <div className="card" key={name}>
              <h3>{name}</h3>
              <p>{description}</p>
              <span className="pill info">{path}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Command flow</h2>
            <p>The command produces proof material, not runtime mutation.</p>
          </div>
          <span className="pill info">dry-run</span>
        </div>
        <div className="grid">
          {commandFlow.map(([name, description]) => (
            <div className="card" key={name}>
              <h3>{name}</h3>
              <p>{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Blocked gates</h2>
            <p>Each stronger capability still needs deterministic receipts before promotion.</p>
          </div>
          <span className="pill danger">blocked_external</span>
        </div>
        <div className="grid">
          {blockedGates.map(([name, description]) => (
            <div className="card" key={name}>
              <div className="row-between">
                <h3>{name}</h3>
                <span className="pill danger">blocked_external</span>
              </div>
              <p>{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Verification command</h2>
            <p>The checker rebuilds CLI evidence, verifies claims remain false, and writes public proof JSON.</p>
          </div>
          <span className="pill info">deterministic</span>
        </div>
        <pre className="terminal">pnpm run cli-deploy-plan:check</pre>
      </section>
    </div>
  );
}
