import { sitePath } from "../../../lib/site-url";

const publicArtifacts = [
  ["Schema package", "packages/deploy-manifests", "Typed local dry-run manifest schema, validator, and tests."],
  ["Local fixture", "examples/deploy/local-deploy-manifest.example.json", "A safe app deploy plan with all managed promotion gates blocked."],
  ["Strict checker", "scripts/deploy/check-deploy-manifest-intake-public-alpha.cjs", "Deterministic validation and public evidence generation."],
  ["Evidence", "launch/evidence/deploy-manifest-intake-public-alpha.json", "Proof file generated by the local public-alpha checker."],
  ["Public JSON", "apps/web/public/gitcaster-deploy-manifest-intake.json", "Website-readable summary of the accepted local plan and blockers."]
];

const blockedCapabilities = [
  ["Managed runtime", "Deploy receipt, smoke proof, and rollback proof are required first."],
  ["Native storage", "Publish receipt, public read proof, and rollback proof are required first."],
  ["Native domain", "Registry receipt and browser smoke proof are required first."],
  ["Custody", "Signer custody reference and redacted receipt are required first."],
  ["Billing", "Subscription policy and abuse-control proof are required first."],
  ["Production readiness", "Release candidate, audit, node health, storage, deploy, domain, and rollback evidence are required first."]
];

const validationRules = [
  "Only loopback preview URLs are accepted.",
  "Managed runtime, native storage, native domain, custody, billing, rollback, and production claims must remain false.",
  "Retired hosted providers can be listed only as not required for the native path.",
  "Secret-like fields and values are rejected before any runtime action.",
  "Every stronger label needs an explicit proof artifact."
];

export default function DeployManifestIntakeOpenSourcePage() {
  return (
    <div className="stack">
      <section className="section">
        <div className="eyebrow">Open-core layer</div>
        <h1>Deploy manifest intake</h1>
        <p className="lede">
          GitCaster now publishes safe local deployment manifests for app,
          miniapp, website, and developer-tool release planning. This is a
          public-alpha intake layer for dry-run validation, dependency retirement
          markers, and proof blockers before managed promotion.
        </p>
        <div className="actions">
          <a className="button primary" href="https://github.com/casteragents/gitcaster/tree/main/packages/deploy-manifests">Schema source</a>
          <a className="button" href="https://github.com/casteragents/gitcaster/tree/main/examples/deploy">Fixture</a>
          <a className="button" href={sitePath("/gitcaster-deploy-manifest-intake.json")}>Evidence JSON</a>
          <a className="button" href={sitePath("/status")}>Status table</a>
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Public artifacts</h2>
            <p>These files let contributors plan releases without touching managed infrastructure.</p>
          </div>
          <span className="pill good">public-alpha</span>
        </div>
        <div className="grid">
          {publicArtifacts.map(([name, path, description]) => (
            <div className="card" key={name}>
              <h3>{name}</h3>
              <p>{description}</p>
              <span className="pill info">{path}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Validation rules</h2>
            <p>The manifest checker accepts local planning and rejects unsupported platform claims.</p>
          </div>
          <span className="pill info">local dry-run</span>
        </div>
        <div className="grid">
          {validationRules.map((rule) => (
            <div className="card" key={rule}>
              <p>{rule}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Blocked promotion gates</h2>
            <p>Promotion remains evidence-gated until operators provide receipts and smoke proof.</p>
          </div>
          <span className="pill danger">blocked_external</span>
        </div>
        <div className="grid">
          {blockedCapabilities.map(([name, description]) => (
            <div className="card" key={name}>
              <div className="row-between">
                <h3>{name}</h3>
                <span className="pill danger">blocked_external</span>
              </div>
              <p>{description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Verification command</h2>
            <p>The checker builds the package, validates the fixture, writes public JSON, and emits evidence.</p>
          </div>
          <span className="pill info">deterministic</span>
        </div>
        <pre className="terminal">pnpm run deploy-manifest:check</pre>
      </section>
    </div>
  );
}
