import { sitePath } from "../../../lib/site-url";

const publicArtifacts = [
  ["Smoke checker", "scripts/ecosystem/check-app-shell-local-preview-smoke-public-alpha.cjs", "Validates static preview routes and rejects unsupported stronger claims."],
  ["Public proof JSON", "apps/web/public/gitcaster-app-shell-local-preview-smoke.json", "Route smoke status, catalog counts, and blocked capability labels."],
  ["Evidence", "launch/evidence/app-shell-local-preview-smoke-public-alpha.json", "Deterministic public-alpha proof generated by the checker."],
  ["Catalog", "apps/web/public/gitcaster-app-shell-catalog.json", "Source catalog for app and miniapp shell preview routes."]
];

const checkedRoutes = [
  ["/ecosystem", "Catalog directory loads preview entries from the RC manifest."],
  ["/ecosystem/caster-claim-miniapp", "Caster Claim miniapp shell loads as a local preview surface."],
  ["/open-source/app-shell-catalog", "Catalog hardening page loads with proof labels and blocked claims."]
];

const blockedClaims = [
  "native storage publication",
  "native domain mapping",
  "managed runtime endpoint",
  "rollback verification",
  "production readiness"
];

export default function AppShellLocalPreviewSmokePage() {
  return (
    <div className="stack">
      <section className="section">
        <div className="eyebrow">Open-core layer</div>
        <h1>App shell local preview smoke</h1>
        <p className="lede">
          GitCaster now publishes deterministic smoke proof for the static app
          and miniapp preview routes. The proof is useful for contributors who
          want to inspect shell metadata, local pages, and blocked promotion
          claims before any managed runtime or native route proof exists.
        </p>
        <div className="actions">
          <a className="button primary" href={sitePath("/ecosystem")}>Preview directory</a>
          <a className="button" href={sitePath("/gitcaster-app-shell-local-preview-smoke.json")}>Smoke JSON</a>
          <a className="button" href="https://github.com/casteragents/gitcaster/tree/main/scripts/ecosystem">Checker source</a>
          <a className="button" href={sitePath("/open-source/app-shell-catalog")}>Catalog layer</a>
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Checked routes</h2>
            <p>Static preview pages are checked for expected copy and claim boundaries.</p>
          </div>
          <span className="pill good">public-alpha</span>
        </div>
        <div className="grid">
          {checkedRoutes.map(([route, description]) => (
            <div className="card" key={route}>
              <h3>{route}</h3>
              <p>{description}</p>
              <span className="pill info">local preview</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Public artifacts</h2>
            <p>These files are safe contribution surfaces for preview-route review.</p>
          </div>
          <span className="pill good">redacted</span>
        </div>
        <div className="grid">
          {publicArtifacts.map(([name, path, description]) => (
            <div className="card" key={name}>
              <h3>{name}</h3>
              <p>{description}</p>
              <span className="pill info">{path}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Still blocked</h2>
            <p>The smoke layer proves local static page output only. Promotion needs separate evidence.</p>
          </div>
          <span className="pill danger">blocked_external</span>
        </div>
        <div className="grid">
          {blockedClaims.map((claim) => (
            <div className="card" key={claim}>
              <p>{claim}</p>
              <span className="pill danger">blocked_external</span>
            </div>
          ))}
        </div>
      </section>

      <section className="section">
        <div className="section-heading">
          <div>
            <h2>Verification command</h2>
            <p>The checker rebuilds preview smoke evidence and keeps unsupported runtime labels false.</p>
          </div>
          <span className="pill info">deterministic</span>
        </div>
        <pre className="terminal">pnpm run app-shell-preview-smoke:check</pre>
      </section>
    </div>
  );
}
